### PR TITLE
refactor: Upgrade dependencies of the project.

### PR DESCRIPTION
**Pull request by GerardPaligot**
* Upgrade Gradle configuration.
* Upgrade Android Gradle Plugin configuration.
* Upgrade Compose to the latest version.
* Use ViewModel to interact with OpenFeedback instance.

Note: Take care about publish Gradle script. I think it is broken with my comments but I guess we need to rework this part with the migration to Maven Central.

### CODE REVIEW

**Comment by martinbonnin** [comment]
Niiiiice 🤩 !! 

Looks like there are some indentation changes in the diff. Do you mind commiting your `.idea/codeStyles` in this branch so we all use the same settings? 

Looks good to me otherwise! I'll do the mavenCentral migration over the weekend.

**Comment by martinbonnin** [comment]
Also the build failed because the CI now requires Java11. Can you bump the version here https://github.com/paug/openfeedback-android-sdk/blob/master/.github/workflows/ci.yaml#L17 ?

**Comment by GerardPaligot** [comment]
> Looks like there are some indentation changes in the diff. Do you mind commiting your .idea/codeStyles in this branch so we all use the same settings?

Yes, the previous indentation was a little bit weird. Sorry for that, I guess the review was difficult with these changes... But great idea about the codeStyle xml file, added!

> Also the build failed because the CI now requires Java11. Can you bump the version here https://github.com/paug/openfeedback-android-sdk/blob/master/.github/workflows/ci.yaml#L17 ?

Oh, fixed!

I added the usage of MaterialTheme to allow light/dark theme, the visual is the same in light mode:

**Review by martinbonnin — APPROVED** [review]

**Comment by GerardPaligot** [comment]
Great! Thanks for the merge @martinbonnin!!

**Pull request merged**
