### PR TITLE
Road to KMP 🚀

### PR DESCRIPTION
**Pull request by GerardPaligot**
> Warning: Still work in progress

Done:

* Create dedicated Gradle plugin for multiplatform modules
* `openfeedback` module migrated (resources and Firebase dependencies)
* `openfeedback-viewmodel` module migrated (use moko-mvvm and multiplatform locale)
* `openfeedback-m3` module migrated (use compose multiplatform, moko-resources-compose and moko-mvvm-compose)
* Remove Jetpack Compose for Compose Multiplatform
* Support Android and iOS targets

Todo:

* Create sample app for ios
* Check releasing if there is any change required
* Rename GitHub project to `openfeedback-kotlin-sdk`

### CODE REVIEW

**Comment by GerardPaligot** [comment]
Blocker to use KMM-ViewModel https://github.com/rickclephas/KMM-ViewModel/issues/29

**Comment by GerardPaligot** [comment]
@martinbonnin More I'm working on this contribution, less I'm convinced about the multiplatform implementation and the api exposed for Android and iOS projects.

Since I configured iOS targets in Gradle modules with Cocoapod support, the build time increased and got Java memory heap exceptions (probably due to Cocoapod) randomly. What do you think about this and the necessity to use firebase kotlin sdk, moko resources, moko mvvm and multiplatform locale in this library which will be included in the final app? 🤔

**Comment by martinbonnin** [comment]
> got Java memory heap exceptions (probably due to Cocoapod) randomly

"Just" increase JVM heap size?

> What do you think about this and the necessity to use firebase kotlin sdk, moko resources, moko mvvm and multiplatform locale in this library which will be included in the final app?

Well, that's a good one, I'm not sure TBH. I have no experience with either moko resources, moko mvvm or multiplatform locale. I have limited experience with firebase kotlin sdk and I was finding this appealing to be able to share the firebase code (that should really be "just" network calls...)

I realize there are a lot of "just" in my sentences above so if the field reality is different then yea, maybe KMP is not the good choice. It'd be interesting to understand where the limitation lies. If it's OOM then I'm fine giving the Kotlin compiler and Gradle more GBs of RAM (and maybe file a Youtrack if usage is patological).

For build times, might be worth checking K2?

**Comment by martinbonnin** [comment]
There are probably more things to be tweaked but I've seen this working both on Android and iOS, I'll merge the mega-PR as-is and do follow up PRs for the remaining stuff

**Pull request merged**
